### PR TITLE
feat: nginx config for request size and timeouts

### PR DESCRIPTION
**Pull request by abuchanan-airbyte**
Set up some nginx config for request body size and timeouts.

Related issues:
- https://github.com/airbytehq/airbyte/issues/45423
- https://github.com/airbytehq/airbyte/issues/45156
- https://github.com/airbytehq/airbyte/issues/43893
- https://github.com/airbytehq/airbyte-internal-issues/issues/9859

Unfortunately, I think this will only work on new installs or uninstall + reinstall. In my tests, I couldn't get this to update my existing ingress.

The request body size is fairly easy to test by creating a postgres source with lots of tables/columns:
Screenshot 2024-09-20 at 11 47 47 AM

after:
image

I'm not sure how to test the timeout setting yet.

### CODE REVIEW

**Review by colesnodgrass — APPROVED** [review]

**Comment by niveditabaliga-payroc** [comment]
Hi @abuchanan-airbyte. When will this be merged in?

**Comment by niveditabaliga-payroc** [comment]
@abuchanan-airbyte does this merge mean we can repull airbyte using abctl and have the fix?

**Comment by japerry911** [comment]
@niveditabaliga-payroc

**Comment by japerry911** [comment]
@niveditabaliga-payroc 

adding annotation to `ingress-abctl` namespace worked for me -

`kubectl edit ingress ingress-abctl -n airbyte-abctl --kubeconfig ~/.airbyte/abctl/abctl.kubeconfig`

then add under metadata (50m = 50 mb, if you need more add higher number, etc..)...

```yaml
metadata:
  annotations:
     nginx.ingress.kubernetes.io/proxy-body-size: "50m" 
```

Should work momentarily.. Just a temporarily fix though, I don't know if this is best method, but works for me.

**Comment by niveditabaliga-payroc** [comment]
thank you for the input @japerry911 . I will remember this in case we run into this issue again. For the time being, the fix released the day before worked after we ran the following commands
1. curl -LsfS https://get.airbyte.com | bash -
2. abctl local uninstall
3. abctl local install

**Pull request merged**
